name: YSbot
description: 10+ engineer in marine,#Dady of 2 kids,#fall in love with Sujin
meta_description: "리트윗 과 웹어플리케이션 이것저것을 옮겨 담기만 합니다."

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'http://yoseobmite.github.io'
google_analytics: 'UA-108668950-1'
disqus: false
disqus_shortname: 'yoseobmite'

# Details for the RSS feed generator
url:            'http://yoseobmite.github.io'
author:         'Your Name'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:month/:day/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
