# Site Info
title: Young-Seob Kim
tagline: '트윗 그리고 스크렙으로 공부하는것을 남겨봅니다.'
description: '리트윗 과 스크렙으로 한것들입니다 초보라 서툴기 그지 없네요'
baseurl: "/"
url: http://yoseobmite.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Young-Seob Kim
  description: A passionate <strong>developer and retwitter</strong>, learning to be a giant.
  #gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
   # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/yoseobmite/yoseobmite.github.io
    # facebook:  <hide>
    twitter:   https://twitter.com/se6644
    # weibo:     http://weibo.com/41173780
    # email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  #Github Project:
  #  - 'http://yoseobmite.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/Soyeon_in.png
  caption: Original Artwork &copy; <a href="http://yoseobmite.github.io">for Yo-seon Kim</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-108668950-1' # leave blank if you don't want google analytics
disqus_short_name: 'yoseobmite' # leave blank if you don't want disqus

